# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt6.QtCore import QTimer, QUrl
from PyQt6.QtGui import QIcon, QDesktopServices
from PyQt6.QtWidgets import QMessageBox



import Shared_B_AdhocTracker_Logic_Page as Shared_B_AdhocTracker_Logic_Page
import Shared_B_Credentials_Logic_Page as Shared_B_Credentials_Logic_Page
import Shared_B_AirlineCode as Data_B_AirlineCode
import Shared_B_LoadMessage as Shared_B_LoadMessage

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1728, 1110)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(False)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("\n"
"\n"
"QTabBar::tab:selected { /* Styles for the selected tab */\n"
"    \n"
"    background-color:qlineargradient(spread:pad, x1:0.0113636, y1:0.04, x2:1, y2:1, stop:0 rgba(255, 53, 53, 255),         stop:1 rgba(255, 136, 224, 255));\n"
"    border-color: #fff;\n"
"    border-bottom-color: rgb(250, 250, 250); /* same as the pane color */\n"
"    color : #fff;\n"
"    padding: 5px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:!selected { \n"
"    /* Styles for unselected tabs */\n"
"    background-color: rgb(225,225,225);\n"
"    border : 1px solid  rgb(200, 200, 200);\n"
"    color : rgb(0, 0, 0);\n"
"    padding: 5px;\n"
"}")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget_2.setTabsClosable(False)
        self.tabWidget_2.setTabBarAutoHide(False)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.tabWidgetPage2)
        self.tabWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab:selected { /* Styles for the selected tab */\n"
"    background-color:qlineargradient(spread:pad, x1:0.0113636, y1:0.04, x2:1, y2:1, stop:0 rgba(53, 160, 255, 255),         stop:1 rgba(255, 136, 224, 255));\n"
"    border-color: gray;\n"
"    border-bottom-color: rgb(250, 250, 250); /* same as the pane color */\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.A_SingleLocation_Tab = QtWidgets.QWidget()
        self.A_SingleLocation_Tab.setObjectName("A_SingleLocation_Tab")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.A_SingleLocation_Tab)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.A_SingleLocation_Tab)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 326, 100))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.SingleLocation_Airline_CSC_comboBox = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents_3)
        self.SingleLocation_Airline_CSC_comboBox.addItems(Data_B_AirlineCode.csc)
        self.SingleLocation_Airline_CSC_comboBox.setMinimumSize(QtCore.QSize(275, 25))
        self.SingleLocation_Airline_CSC_comboBox.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_Airline_CSC_comboBox.setFont(font)
        self.SingleLocation_Airline_CSC_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.SingleLocation_Airline_CSC_comboBox.setObjectName("SingleLocation_Airline_CSC_comboBox")
        self.gridLayout_30.addWidget(self.SingleLocation_Airline_CSC_comboBox, 1, 0, 1, 1)
        self.SingleLocation_Airline_comboBox = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents_3)
        self.SingleLocation_Airline_comboBox.addItems(Data_B_AirlineCode.airline_code)
        self.SingleLocation_Airline_comboBox.setMinimumSize(QtCore.QSize(275, 25))
        self.SingleLocation_Airline_comboBox.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_Airline_comboBox.setFont(font)
        self.SingleLocation_Airline_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.SingleLocation_Airline_comboBox.setObjectName("SingleLocation_Airline_comboBox")
        self.gridLayout_30.addWidget(self.SingleLocation_Airline_comboBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_30.addItem(spacerItem, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_34.addWidget(self.scrollArea_2, 19, 0, 1, 2)
        self.SingleLocation_Airline_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_Airline_label.setFont(font)
        self.SingleLocation_Airline_label.setObjectName("SingleLocation_Airline_label")
        self.gridLayout_34.addWidget(self.SingleLocation_Airline_label, 18, 0, 1, 2)
        self.SingleLocation_ValidityTo_textbox = QtWidgets.QTextEdit(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_ValidityTo_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.SingleLocation_ValidityTo_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.SingleLocation_ValidityTo_textbox.setFont(font)
        self.SingleLocation_ValidityTo_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.SingleLocation_ValidityTo_textbox.setTabChangesFocus(True)
        self.SingleLocation_ValidityTo_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.SingleLocation_ValidityTo_textbox.setTabStopDistance(80.0)
        self.SingleLocation_ValidityTo_textbox.setObjectName("SingleLocation_ValidityTo_textbox")
        self.gridLayout_34.addWidget(self.SingleLocation_ValidityTo_textbox, 10, 1, 1, 1)
        self.SingleLocation_AttachFile_button = QtWidgets.QPushButton(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_AttachFile_button.setMinimumSize(QtCore.QSize(330, 25))
        self.SingleLocation_AttachFile_button.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_AttachFile_button.setFont(font)
        self.SingleLocation_AttachFile_button.setStyleSheet("QPushButton\n"
"{\n"
"color : rgb(0,0,0);\n"
"border : 1px solid  rgb(100, 100, 100);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;\n"
"background-color: rgb(255,255,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"\n"
"\n"
"    border : 2px solid  rgb(0, 0, 0);\n"
"    \n"
"}\n"
"")
        self.SingleLocation_AttachFile_button.setFlat(False)
        self.SingleLocation_AttachFile_button.setObjectName("SingleLocation_AttachFile_button")
        self.gridLayout_34.addWidget(self.SingleLocation_AttachFile_button, 7, 0, 1, 2)
        self.SingleLocation_Priority_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_Priority_label.setFont(font)
        self.SingleLocation_Priority_label.setObjectName("SingleLocation_Priority_label")
        self.gridLayout_34.addWidget(self.SingleLocation_Priority_label, 12, 0, 1, 1)
        self.SingleLocation_AttachLink_textBrowser = QtWidgets.QTextBrowser(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_AttachLink_textBrowser.setMinimumSize(QtCore.QSize(330, 25))
        self.SingleLocation_AttachLink_textBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_AttachLink_textBrowser.setFont(font)
        self.SingleLocation_AttachLink_textBrowser.setStyleSheet("QTextBrowser\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.SingleLocation_AttachLink_textBrowser.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextEditorInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.SingleLocation_AttachLink_textBrowser.setOpenExternalLinks(False)
        self.SingleLocation_AttachLink_textBrowser.setObjectName("SingleLocation_AttachLink_textBrowser")
        self.gridLayout_34.addWidget(self.SingleLocation_AttachLink_textBrowser, 4, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem1, 2, 0, 1, 2)
        self.SingleLocation_SenderName_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_SenderName_label.setMinimumSize(QtCore.QSize(0, 0))
        self.SingleLocation_SenderName_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_SenderName_label.setFont(font)
        self.SingleLocation_SenderName_label.setObjectName("SingleLocation_SenderName_label")
        self.gridLayout_34.addWidget(self.SingleLocation_SenderName_label, 0, 0, 1, 1)
        self.SingleLocation_ValidityTo_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_ValidityTo_label.setFont(font)
        self.SingleLocation_ValidityTo_label.setObjectName("SingleLocation_ValidityTo_label")
        self.gridLayout_34.addWidget(self.SingleLocation_ValidityTo_label, 9, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(247, 441, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_34.addItem(spacerItem2, 20, 0, 1, 2)
        self.SingleLocation_Submit_button = QtWidgets.QPushButton(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_Submit_button.clicked.connect(lambda:(Shared_B_LoadMessage.show_message2(self), Shared_B_AdhocTracker_Logic_Page.AdhocTrackerButtonFunctionality.SingleLocation_Submit_button_Clicked(self, self.msg)))
        self.SingleLocation_Submit_button.setMinimumSize(QtCore.QSize(250, 30))
        self.SingleLocation_Submit_button.setMaximumSize(QtCore.QSize(9999, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_Submit_button.setFont(font)
        self.SingleLocation_Submit_button.setStyleSheet("QPushButton\n"
"{\n"
"color : #fff;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 10px;\n"
"background-color: rgb(33, 126, 70);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"\n"
"    background-color: rgb(58, 202, 111);\n"
"    border : #fff;\n"
"    \n"
"}\n"
"")
        self.SingleLocation_Submit_button.setObjectName("SingleLocation_Submit_button")
        self.gridLayout_34.addWidget(self.SingleLocation_Submit_button, 21, 0, 1, 2)
        self.SingleLocation_ValidityFrom_textbox = QtWidgets.QTextEdit(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_ValidityFrom_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.SingleLocation_ValidityFrom_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.SingleLocation_ValidityFrom_textbox.setFont(font)
        self.SingleLocation_ValidityFrom_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.SingleLocation_ValidityFrom_textbox.setTabChangesFocus(True)
        self.SingleLocation_ValidityFrom_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.SingleLocation_ValidityFrom_textbox.setTabStopDistance(80.0)
        self.SingleLocation_ValidityFrom_textbox.setObjectName("SingleLocation_ValidityFrom_textbox")
        self.gridLayout_34.addWidget(self.SingleLocation_ValidityFrom_textbox, 10, 0, 1, 1)
        self.SingleLocation_Identifier_textbox = QtWidgets.QTextEdit(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_Identifier_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.SingleLocation_Identifier_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.SingleLocation_Identifier_textbox.setFont(font)
        self.SingleLocation_Identifier_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.SingleLocation_Identifier_textbox.setTabChangesFocus(True)
        self.SingleLocation_Identifier_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.SingleLocation_Identifier_textbox.setTabStopDistance(80.0)
        self.SingleLocation_Identifier_textbox.setPlaceholderText("")
        self.SingleLocation_Identifier_textbox.setObjectName("SingleLocation_Identifier_textbox")
        self.gridLayout_34.addWidget(self.SingleLocation_Identifier_textbox, 16, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem3, 5, 0, 1, 2)
        self.SingleLocation_Identifier_comboBox = QtWidgets.QComboBox(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_Identifier_comboBox.setMinimumSize(QtCore.QSize(160, 25))
        self.SingleLocation_Identifier_comboBox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_Identifier_comboBox.setFont(font)
        self.SingleLocation_Identifier_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.SingleLocation_Identifier_comboBox.setPlaceholderText("")
        self.SingleLocation_Identifier_comboBox.setObjectName("SingleLocation_Identifier_comboBox")
        self.gridLayout_34.addWidget(self.SingleLocation_Identifier_comboBox, 16, 0, 1, 1)
        self.SingleLocation_ValidityFrom_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_ValidityFrom_label.setFont(font)
        self.SingleLocation_ValidityFrom_label.setObjectName("SingleLocation_ValidityFrom_label")
        self.gridLayout_34.addWidget(self.SingleLocation_ValidityFrom_label, 9, 0, 1, 1)
        self.SingleLocation_SenderName_textbox = QtWidgets.QTextEdit(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_SenderName_textbox.setMinimumSize(QtCore.QSize(330, 25))
        self.SingleLocation_SenderName_textbox.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.SingleLocation_SenderName_textbox.setFont(font)
        self.SingleLocation_SenderName_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.SingleLocation_SenderName_textbox.setTabChangesFocus(True)
        self.SingleLocation_SenderName_textbox.setObjectName("SingleLocation_SenderName_textbox")
        self.gridLayout_34.addWidget(self.SingleLocation_SenderName_textbox, 1, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem4, 11, 0, 1, 2)
        self.SingleLocation_AttachFile_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_AttachFile_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_AttachFile_label.setFont(font)
        self.SingleLocation_AttachFile_label.setObjectName("SingleLocation_AttachFile_label")
        self.gridLayout_34.addWidget(self.SingleLocation_AttachFile_label, 6, 0, 1, 1)
        self.SingleLocation_AttachLink_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_AttachLink_label.setMinimumSize(QtCore.QSize(0, 0))
        self.SingleLocation_AttachLink_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_AttachLink_label.setFont(font)
        self.SingleLocation_AttachLink_label.setObjectName("SingleLocation_AttachLink_label")
        self.gridLayout_34.addWidget(self.SingleLocation_AttachLink_label, 3, 0, 1, 1)
        self.SingleLocation_Identifier_label = QtWidgets.QLabel(parent=self.A_SingleLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.SingleLocation_Identifier_label.setFont(font)
        self.SingleLocation_Identifier_label.setObjectName("SingleLocation_Identifier_label")
        self.gridLayout_34.addWidget(self.SingleLocation_Identifier_label, 15, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem5, 8, 0, 1, 2)
        self.SingleLocation_Priority_comboBox = QtWidgets.QComboBox(parent=self.A_SingleLocation_Tab)
        self.SingleLocation_Priority_comboBox.setMinimumSize(QtCore.QSize(330, 25))
        self.SingleLocation_Priority_comboBox.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.SingleLocation_Priority_comboBox.setFont(font)
        self.SingleLocation_Priority_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.SingleLocation_Priority_comboBox.setPlaceholderText("")
        self.SingleLocation_Priority_comboBox.setObjectName("SingleLocation_Priority_comboBox")
        self.SingleLocation_Priority_comboBox.addItem("")
        self.SingleLocation_Priority_comboBox.addItem("")
        self.SingleLocation_Priority_comboBox.addItem("")
        self.SingleLocation_Priority_comboBox.addItem("")
        self.gridLayout_34.addWidget(self.SingleLocation_Priority_comboBox, 13, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem6, 14, 0, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_34.addItem(spacerItem7, 17, 0, 1, 2)
        self.tabWidget.addTab(self.A_SingleLocation_Tab, "")
        self.B_MultiLocation_Tab = QtWidgets.QWidget()
        self.B_MultiLocation_Tab.setObjectName("B_MultiLocation_Tab")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.B_MultiLocation_Tab)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.MultiLocation_ValidityTo_textbox = QtWidgets.QTextEdit(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_ValidityTo_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.MultiLocation_ValidityTo_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.MultiLocation_ValidityTo_textbox.setFont(font)
        self.MultiLocation_ValidityTo_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.MultiLocation_ValidityTo_textbox.setTabChangesFocus(True)
        self.MultiLocation_ValidityTo_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.MultiLocation_ValidityTo_textbox.setTabStopDistance(80.0)
        self.MultiLocation_ValidityTo_textbox.setObjectName("MultiLocation_ValidityTo_textbox")
        self.gridLayout_32.addWidget(self.MultiLocation_ValidityTo_textbox, 10, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem8, 14, 0, 1, 2)
        self.MultiLocation_Identifier_comboBox = QtWidgets.QComboBox(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_Identifier_comboBox.setMinimumSize(QtCore.QSize(160, 25))
        self.MultiLocation_Identifier_comboBox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_Identifier_comboBox.setFont(font)
        self.MultiLocation_Identifier_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_Identifier_comboBox.setPlaceholderText("")
        self.MultiLocation_Identifier_comboBox.setObjectName("MultiLocation_Identifier_comboBox")
        self.gridLayout_32.addWidget(self.MultiLocation_Identifier_comboBox, 16, 0, 1, 1)
        self.MultiLocation_SenderName_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_SenderName_label.setFont(font)
        self.MultiLocation_SenderName_label.setObjectName("MultiLocation_SenderName_label")
        self.gridLayout_32.addWidget(self.MultiLocation_SenderName_label, 0, 0, 1, 1)
        self.MultiLocation_ValidityFrom_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_ValidityFrom_label.setFont(font)
        self.MultiLocation_ValidityFrom_label.setObjectName("MultiLocation_ValidityFrom_label")
        self.gridLayout_32.addWidget(self.MultiLocation_ValidityFrom_label, 9, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem9, 2, 0, 1, 2)
        self.MultiLocation_AttachLink_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_AttachLink_label.setFont(font)
        self.MultiLocation_AttachLink_label.setObjectName("MultiLocation_AttachLink_label")
        self.gridLayout_32.addWidget(self.MultiLocation_AttachLink_label, 3, 0, 1, 1)
        self.MultiLocation_ValidityFrom_textbox = QtWidgets.QTextEdit(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_ValidityFrom_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.MultiLocation_ValidityFrom_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.MultiLocation_ValidityFrom_textbox.setFont(font)
        self.MultiLocation_ValidityFrom_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.MultiLocation_ValidityFrom_textbox.setTabChangesFocus(True)
        self.MultiLocation_ValidityFrom_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.MultiLocation_ValidityFrom_textbox.setTabStopDistance(80.0)
        self.MultiLocation_ValidityFrom_textbox.setObjectName("MultiLocation_ValidityFrom_textbox")
        self.gridLayout_32.addWidget(self.MultiLocation_ValidityFrom_textbox, 10, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.B_MultiLocation_Tab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 326, 450))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.MultiLocation_CSC_comboBox_7 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_7.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_7.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_7.setFont(font)
        self.MultiLocation_CSC_comboBox_7.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_7.setObjectName("MultiLocation_CSC_comboBox_7")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_7, 7, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_5 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_5.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_5.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_5.setFont(font)
        self.MultiLocation_CSC_comboBox_5.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_5.setObjectName("MultiLocation_CSC_comboBox_5")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_5, 5, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_10 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_10.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_10.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_10.setFont(font)
        self.MultiLocation_CSC_comboBox_10.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_10.setObjectName("MultiLocation_CSC_comboBox_10")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_10, 10, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_8 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_8.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_8.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_8.setFont(font)
        self.MultiLocation_CSC_comboBox_8.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_8.setObjectName("MultiLocation_CSC_comboBox_8")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_8, 8, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_9 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_9.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_9.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_9.setFont(font)
        self.MultiLocation_CSC_comboBox_9.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_9.setObjectName("MultiLocation_CSC_comboBox_9")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_9, 9, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_3 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_3.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_3.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_3.setFont(font)
        self.MultiLocation_CSC_comboBox_3.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_3.setObjectName("MultiLocation_CSC_comboBox_3")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_3, 3, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_1 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_1.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_1.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_1.setFont(font)
        self.MultiLocation_CSC_comboBox_1.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_1.setObjectName("MultiLocation_CSC_comboBox_1")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_1, 1, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_2 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_2.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_2.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_2.setFont(font)
        self.MultiLocation_CSC_comboBox_2.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_2.setObjectName("MultiLocation_CSC_comboBox_2")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_2, 2, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_6 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_6.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_6.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_6.setFont(font)
        self.MultiLocation_CSC_comboBox_6.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_6.setObjectName("MultiLocation_CSC_comboBox_6")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_6, 6, 0, 1, 1)
        self.MultiLocation_CSC_comboBox_4 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_CSC_comboBox_4.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_CSC_comboBox_4.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_CSC_comboBox_4.setFont(font)
        self.MultiLocation_CSC_comboBox_4.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_CSC_comboBox_4.setObjectName("MultiLocation_CSC_comboBox_4")
        self.gridLayout_29.addWidget(self.MultiLocation_CSC_comboBox_4, 4, 0, 1, 1)
        self.MultiLocation_Airline_comboBox = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.MultiLocation_Airline_comboBox.setMinimumSize(QtCore.QSize(275, 25))
        self.MultiLocation_Airline_comboBox.setMaximumSize(QtCore.QSize(275, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_Airline_comboBox.setFont(font)
        self.MultiLocation_Airline_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_Airline_comboBox.setObjectName("MultiLocation_Airline_comboBox")
        self.gridLayout_29.addWidget(self.MultiLocation_Airline_comboBox, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_29.addItem(spacerItem10, 11, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_32.addWidget(self.scrollArea, 19, 0, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem11, 8, 0, 1, 2)
        spacerItem12 = QtWidgets.QSpacerItem(247, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem12, 20, 0, 1, 1)
        self.MultiLocation_ValidityTo_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_ValidityTo_label.setFont(font)
        self.MultiLocation_ValidityTo_label.setObjectName("MultiLocation_ValidityTo_label")
        self.gridLayout_32.addWidget(self.MultiLocation_ValidityTo_label, 9, 1, 1, 1)
        self.MultiLocation_Identifier_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_Identifier_label.setFont(font)
        self.MultiLocation_Identifier_label.setObjectName("MultiLocation_Identifier_label")
        self.gridLayout_32.addWidget(self.MultiLocation_Identifier_label, 15, 0, 1, 1)
        self.MultiLocation_Airline_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_Airline_label.setFont(font)
        self.MultiLocation_Airline_label.setObjectName("MultiLocation_Airline_label")
        self.gridLayout_32.addWidget(self.MultiLocation_Airline_label, 18, 0, 1, 2)
        self.MultiLocation_AttachFile_button = QtWidgets.QPushButton(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_AttachFile_button.setMinimumSize(QtCore.QSize(330, 25))
        self.MultiLocation_AttachFile_button.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_AttachFile_button.setFont(font)
        self.MultiLocation_AttachFile_button.setStyleSheet("QPushButton\n"
"{\n"
"color : rgb(0,0,0);\n"
"border : 1px solid  rgb(100, 100, 100);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;\n"
"background-color: rgb(255,255,255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"\n"
"\n"
"    border : 2px solid  rgb(0, 0, 0);\n"
"    \n"
"}\n"
"")
        self.MultiLocation_AttachFile_button.setObjectName("MultiLocation_AttachFile_button")
        self.gridLayout_32.addWidget(self.MultiLocation_AttachFile_button, 7, 0, 1, 2)
        self.MultiLocation_Submit_button = QtWidgets.QPushButton(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_Submit_button.setMinimumSize(QtCore.QSize(250, 30))
        self.MultiLocation_Submit_button.setMaximumSize(QtCore.QSize(9999, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_Submit_button.setFont(font)
        self.MultiLocation_Submit_button.setStyleSheet("QPushButton\n"
"{\n"
"color : #fff;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 10px;\n"
"background-color: rgb(33, 126, 70);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"\n"
"    background-color: rgb(58, 202, 111);\n"
"    border : #fff;\n"
"    \n"
"}\n"
"")
        self.MultiLocation_Submit_button.setObjectName("MultiLocation_Submit_button")
        self.gridLayout_32.addWidget(self.MultiLocation_Submit_button, 21, 0, 1, 2)
        self.MultiLocation_Priority_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_Priority_label.setFont(font)
        self.MultiLocation_Priority_label.setObjectName("MultiLocation_Priority_label")
        self.gridLayout_32.addWidget(self.MultiLocation_Priority_label, 12, 0, 1, 2)
        self.MultiLocation_SenderName_textbox = QtWidgets.QTextEdit(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_SenderName_textbox.setMinimumSize(QtCore.QSize(330, 25))
        self.MultiLocation_SenderName_textbox.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.MultiLocation_SenderName_textbox.setFont(font)
        self.MultiLocation_SenderName_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.MultiLocation_SenderName_textbox.setTabChangesFocus(True)
        self.MultiLocation_SenderName_textbox.setTabStopDistance(80.0)
        self.MultiLocation_SenderName_textbox.setObjectName("MultiLocation_SenderName_textbox")
        self.gridLayout_32.addWidget(self.MultiLocation_SenderName_textbox, 1, 0, 1, 2)
        self.MultiLocation_Priority_comboBox = QtWidgets.QComboBox(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_Priority_comboBox.setMinimumSize(QtCore.QSize(330, 25))
        self.MultiLocation_Priority_comboBox.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultiLocation_Priority_comboBox.setFont(font)
        self.MultiLocation_Priority_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 5px;\n"
"    border :1px solid  rgb(100, 100, 100);\n"
"    border-radius: 4px; /* Rounded corners */\n"
"    background-color: #f0f0f0; /* Light background */\n"
"    selection-background-color: #5a5a5a; /* Selection color */\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #5a5a5a; /* Darker border on hover */\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center; /* Dropdown button on the right center */\n"
"    width: 20px; /* Width of the dropdown button */\n"
"    border-left-width: 1px;\n"
"    border-left-color: #adb2b5; /* Lighter border color for the dropdown button */\n"
"    border-left-style: solid; /* Solid border style */\n"
"    border-top-right-radius: 3px; /* Rounded corner for the top right of the dropdown */\n"
"    border-bottom-right-radius: 3px; /* Rounded corner for the bottom right of the dropdown */\n"
"}\n"
"\n"
"\n"
"\n"
"/* Changing the dropdown menu\'s appearance */\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #c8c8c8; /* Border color for the dropdown */\n"
"    selection-background-color: #e0e0e0; /* Background color for selected item */\n"
"    background-color: #ffffff; /* Dropdown background color */\n"
"    border-radius: 2px; /* Rounded corners for the dropdown */\n"
"}\n"
"\n"
"/* Style for editable combo boxes */\n"
"QComboBox:editable {\n"
"    background-color: #ffffff; /* Background color for editable state */\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     background: #f0f0f0; /* Non-editable background */\n"
"}\n"
"\n"
"QComboBox:on { /* when the dropdown is open */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #6d6d6d; /* Background color for selection */\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background: #e5e5e5; /* Light hover background for the dropdown button */\n"
"}\n"
"")
        self.MultiLocation_Priority_comboBox.setPlaceholderText("")
        self.MultiLocation_Priority_comboBox.setObjectName("MultiLocation_Priority_comboBox")
        self.MultiLocation_Priority_comboBox.addItem("")
        self.MultiLocation_Priority_comboBox.addItem("")
        self.MultiLocation_Priority_comboBox.addItem("")
        self.MultiLocation_Priority_comboBox.addItem("")
        self.gridLayout_32.addWidget(self.MultiLocation_Priority_comboBox, 13, 0, 1, 1)
        self.MultiLocation_AttachFile_label = QtWidgets.QLabel(parent=self.B_MultiLocation_Tab)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        self.MultiLocation_AttachFile_label.setFont(font)
        self.MultiLocation_AttachFile_label.setObjectName("MultiLocation_AttachFile_label")
        self.gridLayout_32.addWidget(self.MultiLocation_AttachFile_label, 6, 0, 1, 1)
        self.MultipleLocation_AttachLink_textBrowser = QtWidgets.QTextBrowser(parent=self.B_MultiLocation_Tab)
        self.MultipleLocation_AttachLink_textBrowser.setMinimumSize(QtCore.QSize(330, 25))
        self.MultipleLocation_AttachLink_textBrowser.setMaximumSize(QtCore.QSize(330, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.MultipleLocation_AttachLink_textBrowser.setFont(font)
        self.MultipleLocation_AttachLink_textBrowser.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.MultipleLocation_AttachLink_textBrowser.setReadOnly(False)
        self.MultipleLocation_AttachLink_textBrowser.setOpenExternalLinks(True)
        self.MultipleLocation_AttachLink_textBrowser.setObjectName("MultipleLocation_AttachLink_textBrowser")
        self.gridLayout_32.addWidget(self.MultipleLocation_AttachLink_textBrowser, 4, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem13, 11, 0, 1, 2)
        spacerItem14 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem14, 5, 0, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(247, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_32.addItem(spacerItem15, 17, 0, 1, 2)
        self.MultiLocation_Identifier_textbox = QtWidgets.QTextEdit(parent=self.B_MultiLocation_Tab)
        self.MultiLocation_Identifier_textbox.setMinimumSize(QtCore.QSize(160, 25))
        self.MultiLocation_Identifier_textbox.setMaximumSize(QtCore.QSize(160, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        self.MultiLocation_Identifier_textbox.setFont(font)
        self.MultiLocation_Identifier_textbox.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(100, 100, 100);\n"
"\n"
"\n"
"border-radius: 4px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.MultiLocation_Identifier_textbox.setTabChangesFocus(True)
        self.MultiLocation_Identifier_textbox.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.NoWrap)
        self.MultiLocation_Identifier_textbox.setTabStopDistance(80.0)
        self.MultiLocation_Identifier_textbox.setPlaceholderText("")
        self.MultiLocation_Identifier_textbox.setObjectName("MultiLocation_Identifier_textbox")
        self.gridLayout_32.addWidget(self.MultiLocation_Identifier_textbox, 16, 1, 1, 1)
        self.tabWidget.addTab(self.B_MultiLocation_Tab, "")
        self.gridLayout_35.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.AdhocTracker_CreateProject_Frame = QtWidgets.QWidget(parent=self.tabWidgetPage2)
        self.AdhocTracker_CreateProject_Frame.setMinimumSize(QtCore.QSize(0, 0))
        self.AdhocTracker_CreateProject_Frame.setMaximumSize(QtCore.QSize(9999999, 9999999))
        self.AdhocTracker_CreateProject_Frame.setStyleSheet("QWidget#AdhocTracker_CreateProject_Frame_2\n"
"\n"
"\n"
"{border : 0px solid  rgb(200, 200, 200);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"\n"
"border-radius: 10px;\n"
"\n"
"}")
        self.AdhocTracker_CreateProject_Frame.setObjectName("AdhocTracker_CreateProject_Frame")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.AdhocTracker_CreateProject_Frame)
        self.gridLayout_28.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_28.setSpacing(2)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.AdhocTracker_CreateProject_Display = QtWidgets.QTextEdit(parent=self.AdhocTracker_CreateProject_Frame)
        self.AdhocTracker_CreateProject_Display.setStyleSheet("QTextEdit\n"
"\n"
"{border : 1px solid  rgb(200, 200, 200);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 10px;\n"
"background-color: rgb(250,250,250);\n"
"\n"
"}")
        self.AdhocTracker_CreateProject_Display.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextEditorInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.AdhocTracker_CreateProject_Display.setObjectName("AdhocTracker_CreateProject_Display")
        self.gridLayout_28.addWidget(self.AdhocTracker_CreateProject_Display, 3, 0, 1, 5)
        self.gridLayout_35.addWidget(self.AdhocTracker_CreateProject_Frame, 1, 1, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_35.addItem(spacerItem16, 0, 1, 1, 2)
        self.tabWidget_2.addTab(self.tabWidgetPage2, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1728, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SingleLocation_Airline_CSC_comboBox.setPlaceholderText(_translate("MainWindow", "CSC"))
        self.SingleLocation_Airline_comboBox.setPlaceholderText(_translate("MainWindow", "Airline"))
        self.SingleLocation_Airline_label.setText(_translate("MainWindow", "Airline Info:"))
        self.SingleLocation_ValidityTo_textbox.setPlaceholderText(_translate("MainWindow", "To"))
        self.SingleLocation_AttachFile_button.setText(_translate("MainWindow", "Attach a file"))
        self.SingleLocation_Priority_label.setText(_translate("MainWindow", "Priority:"))
        self.SingleLocation_AttachLink_textBrowser.setPlaceholderText(_translate("MainWindow", "Attach a link"))
        self.SingleLocation_SenderName_label.setText(_translate("MainWindow", "Sender Info:"))
        self.SingleLocation_ValidityTo_label.setText(_translate("MainWindow", "Validity To:"))
        self.SingleLocation_Submit_button.setText(_translate("MainWindow", "Submit"))
        self.SingleLocation_ValidityFrom_textbox.setPlaceholderText(_translate("MainWindow", "From"))
        self.SingleLocation_ValidityFrom_label.setText(_translate("MainWindow", "Validity From:"))
        self.SingleLocation_SenderName_textbox.setPlaceholderText(_translate("MainWindow", "Enter your U#"))
        self.SingleLocation_AttachFile_label.setText(_translate("MainWindow", "File:"))
        self.SingleLocation_AttachLink_label.setText(_translate("MainWindow", "Link:"))
        self.SingleLocation_Identifier_label.setText(_translate("MainWindow", "Identifier:"))
        self.SingleLocation_Priority_comboBox.setItemText(0, _translate("MainWindow", "Low"))
        self.SingleLocation_Priority_comboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.SingleLocation_Priority_comboBox.setItemText(2, _translate("MainWindow", "Important"))
        self.SingleLocation_Priority_comboBox.setItemText(3, _translate("MainWindow", "Urgent"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.A_SingleLocation_Tab), _translate("MainWindow", "  Single  "))
        self.MultiLocation_ValidityTo_textbox.setPlaceholderText(_translate("MainWindow", "To"))
        self.MultiLocation_SenderName_label.setText(_translate("MainWindow", "Sender Info:"))
        self.MultiLocation_ValidityFrom_label.setText(_translate("MainWindow", "Validity From:"))
        self.MultiLocation_AttachLink_label.setText(_translate("MainWindow", "Link:"))
        self.MultiLocation_ValidityFrom_textbox.setPlaceholderText(_translate("MainWindow", "From"))
        self.MultiLocation_CSC_comboBox_7.setPlaceholderText(_translate("MainWindow", "CSC #7"))
        self.MultiLocation_CSC_comboBox_5.setPlaceholderText(_translate("MainWindow", "CSC #5"))
        self.MultiLocation_CSC_comboBox_10.setPlaceholderText(_translate("MainWindow", "CSC #10"))
        self.MultiLocation_CSC_comboBox_8.setPlaceholderText(_translate("MainWindow", "CSC #8"))
        self.MultiLocation_CSC_comboBox_9.setPlaceholderText(_translate("MainWindow", "CSC #9"))
        self.MultiLocation_CSC_comboBox_3.setPlaceholderText(_translate("MainWindow", "CSC #3"))
        self.MultiLocation_CSC_comboBox_1.setPlaceholderText(_translate("MainWindow", "CSC #1"))
        self.MultiLocation_CSC_comboBox_2.setPlaceholderText(_translate("MainWindow", "CSC #2"))
        self.MultiLocation_CSC_comboBox_6.setPlaceholderText(_translate("MainWindow", "CSC #6"))
        self.MultiLocation_CSC_comboBox_4.setPlaceholderText(_translate("MainWindow", "CSC #4"))
        self.MultiLocation_Airline_comboBox.setPlaceholderText(_translate("MainWindow", "Airline"))
        self.MultiLocation_ValidityTo_label.setText(_translate("MainWindow", "Validity To:"))
        self.MultiLocation_Identifier_label.setText(_translate("MainWindow", "Identifier:"))
        self.MultiLocation_Airline_label.setText(_translate("MainWindow", "Airline Info:"))
        self.MultiLocation_AttachFile_button.setText(_translate("MainWindow", "Attach a file"))
        self.MultiLocation_Submit_button.setText(_translate("MainWindow", "Submit"))
        self.MultiLocation_Priority_label.setText(_translate("MainWindow", "Priority:"))
        self.MultiLocation_SenderName_textbox.setPlaceholderText(_translate("MainWindow", "Enter your U#"))
        self.MultiLocation_Priority_comboBox.setItemText(0, _translate("MainWindow", "Low"))
        self.MultiLocation_Priority_comboBox.setItemText(1, _translate("MainWindow", "Medium"))
        self.MultiLocation_Priority_comboBox.setItemText(2, _translate("MainWindow", "Important"))
        self.MultiLocation_Priority_comboBox.setItemText(3, _translate("MainWindow", "Urgent"))
        self.MultiLocation_AttachFile_label.setText(_translate("MainWindow", "File:"))
        self.MultipleLocation_AttachLink_textBrowser.setPlaceholderText(_translate("MainWindow", "Attach a link"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.B_MultiLocation_Tab), _translate("MainWindow", "  Multi  "))
        self.AdhocTracker_CreateProject_Display.setPlaceholderText(_translate("MainWindow", "Enter your message here.."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Create a New Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
