name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version you need

    # Step 3: Install system dependencies for PyQt GUI testing
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libgl1-mesa-dev libxkbcommon-x11-0 xvfb

    # Step 4: Cache pip dependencies to speed up workflow
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 5: Install Python dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 6: Run tests with Xvfb (X virtual framebuffer)
    - name: Run Tests
      run: |
        # Start X virtual framebuffer
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99

        # Run tests
        pytest

    # (Optional) Step 7: Linting with flake8
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
